### ISSUE TITLE
getCasesByCount API is broken

### ISSUE THREAD

**Issue by strainu** [geospatialorg/covid19#3]
`TypeError: Cannot read property 'split' of undefined
    at verifyToken (/home/geospatial/covid19/api/routes/index.js:5:43)
    at Layer.handle [as handle_request] (/home/geospatial/covid19/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/geospatial/covid19/node_modules/express/lib/router/index.js:317:13)
    at /home/geospatial/covid19/node_modules/express/lib/router/index.js:284:7
    at param (/home/geospatial/covid19/node_modules/express/lib/router/index.js:354:14)
    at param (/home/geospatial/covid19/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/geospatial/covid19/node_modules/express/lib/router/index.js:410:3)
    at next (/home/geospatial/covid19/node_modules/express/lib/router/index.js:275:10)
    at /home/geospatial/covid19/node_modules/express/lib/router/index.js:635:15
    at next (/home/geospatial/covid19/node_modules/express/lib/router/index.js:260:14)`

**Comment by CristiBB** [comment]
It was a typo in the published link, it has been fixed.
